DA-511: RAG with Couchbase and Cohere Notebook
couchbase-examples/vector-search-cookbook pull request #1
Opened 2024-08-06 07:53 UTC by teetangh

2024-08-07 08:44 UTC, lokesh-couchbase commented on cohere/search.py
> +import cohere
langchain-cohere?

2024-08-07 08:45 UTC, lokesh-couchbase commented
Other comments are same as in #2

2024-08-08 08:34 UTC, lokesh-couchbase commented
Why are you not using Command R+ model for LLM?

2024-08-12 09:26 UTC, teetangh commented on cohere/search.py
> +import cohere
fixed it

2024-08-12 16:41 UTC, nithishr commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +            "Requirement already satisfied: cohere in /usr/local/lib/python3.10/dist-packages (5.6.2)\n",
You should only install langchain-cohere

2024-08-12 16:42 UTC, nithishr commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +            "Requirement already satisfied: openai<2.0.0,>=1.32.0 in /usr/local/lib/python3.10/dist-packages (from langchain_openai) (1.39.0)\n",
You should cohere's LLM instetad of OpenAI

2024-08-12 16:43 UTC, nithishr commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +        "def main():\n",
Typically in Notebooks, you write the code without functions in smaller sections explaining them as you write the sections.

2024-08-12 16:43 UTC, nithishr commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +        "This function initializes and returns a CouchbaseCache, which is used for caching purposes within the application. The cache helps in reducing redundant computations and improves the perform
This explanation is quite vague & not accurate.

2024-08-12 16:44 UTC, nithishr commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
Also, we should create the vector index from scratch.

2024-08-12 16:46 UTC, nithishr commented on cohere/search.py
Why are we replicating the same code in two places (Py & Notebook)?

2024-08-14 06:49 UTC, teetangh commented on cohere/search.py
The Python version is modular while the notebook version is non-modular and more focussed to describe the approach and run each each block at a time and see the output

2024-08-14 06:51 UTC, teetangh commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +            "Requirement already satisfied: openai<2.0.0,>=1.32.0 in /usr/local/lib/python3.10/dist-packages (from langchain_openai) (1.39.0)\n",
used cohere's llm

2024-08-14 06:51 UTC, teetangh commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
created the vector index from scratch with proper error handling

2024-08-20 09:06 UTC, teetangh commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +            "Requirement already satisfied: cohere in /usr/local/lib/python3.10/dist-packages (5.6.2)\n",
done

2024-08-20 09:06 UTC, teetangh commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +        "This function initializes and returns a CouchbaseCache, which is used for caching purposes within the application. The cache helps in reducing redundant computations and improves the perform
updated with more elaborate explaination

2024-08-20 09:07 UTC, teetangh commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +        "def main():\n",
updated

2024-08-22 09:34 UTC, nithishr requested changes

2024-08-22 09:34 UTC, nithishr commented on cohere/requirements.txt
> +langchain-openai
You need to pin the dependencies. 
Also why do you need openai?

2024-08-22 09:34 UTC, nithishr commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +        "The script attempts to establish a connection to the Couchbase database using the credentials retrieved from the environment variables. Couchbase is a NoSQL database known for its flexibilit
The credentials are not from the environment variables

2024-08-22 09:34 UTC, nithishr commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +    {
Why is this commented out? Remove it if you don't need

2024-08-22 09:34 UTC, nithishr commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +            "Semantic Search Results (completed in 0.53 seconds):\n",
I would clean this up before running the notebook to not have these repeated results.

2024-08-22 09:34 UTC, nithishr commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +          ]
Also, can you add an extra cell that showcases the use of the Cache?
Currently, you are caching the response but it is not being used.

2024-08-22 09:34 UTC, nithishr commented on cohere/search.py
> +            except CollectionNotFoundException:
Do you get this exception here? It is only creating a reference to the collection here & you would get the exception only when you perform an operation on the collection.

2024-08-22 09:34 UTC, nithishr commented on cohere/search.py
> +            cluster.query(f"CREATE PRIMARY INDEX ON `{bucket_name}`.`{scope_name}`.`{collection_name}`").execute()
You can avoid this error handling by using IF NOT EXISTS clause while creating the index
https://docs.couchbase.com/server/current/n1ql/n1ql-language-reference/createprimaryindex.html#if-not-exists

2024-08-22 09:34 UTC, nithishr commented on cohere/search.py
> +        )
Doesn't the `SearchIndex.from_json()` work? 
It should be the recommended approach here as you have the search index json here already.

2024-08-22 09:34 UTC, nithishr commented on cohere/search.py
Can you please add a single line doc string to each function about its functionality

2024-08-22 09:34 UTC, nithishr commented on cohere/search.py
> +def main():
You can remove this function & instead use the script content under the script check. The function does not do anything special here.

2024-08-23 13:20 UTC, teetangh commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +        "The script attempts to establish a connection to the Couchbase database using the credentials retrieved from the environment variables. Couchbase is a NoSQL database known for its flexibilit
Now i have implemented it from the getpass.getpass method you earlier suggested

2024-08-23 13:21 UTC, teetangh commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +            "Semantic Search Results (completed in 0.53 seconds):\n",
cleared the collection now before using it

2024-08-23 13:21 UTC, teetangh commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +          ]
Shown the use case of cache

2024-08-23 13:22 UTC, teetangh commented on cohere/search.py
> +            except CollectionNotFoundException:
removed this exception handling. Had added it as a precautionary measure

2024-08-23 13:22 UTC, teetangh commented on cohere/search.py
> +            cluster.query(f"CREATE PRIMARY INDEX ON `{bucket_name}`.`{scope_name}`.`{collection_name}`").execute()
Used the "IF NOT EXISTS" clause now

2024-08-23 13:23 UTC, teetangh commented on cohere/search.py
> +        )
Used the `SearchIndex.from_json()` method now

2024-08-23 13:23 UTC, teetangh commented on cohere/search.py
> +def main():
removed it

2024-08-27 09:47 UTC, nithishr requested changes

2024-08-27 09:47 UTC, nithishr commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +        "# Install python-dotenv\n",
Is this accurate?

2024-08-27 09:47 UTC, nithishr commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +        "!pip install python-dotenv couchbase datasets langchain_core langchain_cohere langchain_couchbase tqdm"
Do you need all these libraries?

2024-08-27 09:47 UTC, nithishr commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +        "# Loading Environment Variables\n",
What is an environment variable?

2024-08-27 09:47 UTC, nithishr commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +        "# Loading Environment Variables\n",
https://github.com/couchbase-examples/vector-search-cookbook/pull/1#discussion_r1726671084

2024-08-27 09:47 UTC, nithishr commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +        "Semantic search in Couchbase involves converting a query and documents into vector representations using a model like OpenAI's embeddings. These vectors capture the semantic meaning of the t
The similarity metric is user defined

2024-08-27 09:47 UTC, nithishr commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +        "    results = [{'id': doc.metadata.get('id', 'N/A'), 'text': doc.page_content, 'distance': score}\n",
Why do you need to do all this processing here especially considering that you are not doing anything with most of the content?

2024-08-27 09:47 UTC, nithishr commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +            "RAG Response: You appear to have asked a question about the cause of the 1929 Great Depression. I cannot find any direct answer to your question in the provided context. However, it is b
Is this example accurate? The answer is coming entirely from the LLM without any contextual info.

2024-08-27 09:47 UTC, nithishr commented on cohere/requirements.txt
> +couchbase==4.3.0
Check if you need all the dependencies. You don't need some of them for sure.

2024-08-28 08:46 UTC, teetangh commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +        "# Install python-dotenv\n",
removed that unnecessary comment.

2024-08-28 08:47 UTC, teetangh commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +        "!pip install python-dotenv couchbase datasets langchain_core langchain_cohere langchain_couchbase tqdm"
removed python-dotenv, remaining i do require, we can see that we have used them in the cell below

2024-08-28 08:47 UTC, teetangh commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +        "# Loading Environment Variables\n",
Changed it to loading sensitive information

2024-08-28 08:48 UTC, teetangh commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +        "Semantic search in Couchbase involves converting a query and documents into vector representations using a model like OpenAI's embeddings. These vectors capture the semantic meaning of the t
understood. changed it

2024-08-28 08:48 UTC, teetangh commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +        "    results = [{'id': doc.metadata.get('id', 'N/A'), 'text': doc.page_content, 'distance': score}\n",
removed this unnecessary processing

2024-08-28 08:48 UTC, teetangh commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +            "RAG Response: You appear to have asked a question about the cause of the 1929 Great Depression. I cannot find any direct answer to your question in the provided context. However, it is b
Now am using an example that comes from the dataset

2024-08-28 09:04 UTC, teetangh commented on cohere/requirements.txt
> +couchbase==4.3.0
I do need all these dependencies.

`couchbase`: I need this package to connect to Couchbase for managing and interacting with the Couchbase cluster, 

`dotenv`: for loading the .env file in local

`tqdm`: for progress display in long waiting loops

`datasets`: contains loadset for TREC dataset

`langchain_core`: I need this package for building and managing the core components of the LangChain framework. This includes setting up and using language models (LLM), handling document processing with Document, defining custom output parsing with StrOutputParser, and creating and managing prompts using ChatPromptTemplate. The RunnablePassthrough is useful for chaining operations together. Additionally, langchain_core includes the ability to manage global settings and caching, which are important for optimizing performance and managing resources across the system.

`langchain_cohere`: contains ChatCohere for llm model , CohereEmbeddings for embeddings generator 

`langchain_couchbase`: contains CouchbaseCache

2024-08-29 10:27 UTC, nithishr commented on cohere/requirements.txt
> +couchbase==4.3.0
Check what happens when you install `langchain_couchbase` on a fresh environment.

2024-08-29 10:28 UTC, nithishr commented on cohere/RAG_with_Couchbase_and_Cohere.ipynb
> +        "!pip install python-dotenv couchbase datasets langchain_core langchain_cohere langchain_couchbase tqdm"
You need the libraries but do you need to install all of them? Check out transitive dependencies

2024-08-29 13:37 UTC, teetangh commented on cohere/requirements.txt
> +couchbase==4.3.0
removed couchbase, langchain_core and tqdm

2024-08-29 15:51 UTC, nithishr approved these changes

2024-08-29 16:08 UTC, merged