DA-525: RAG with Couchbase and JinaAI Notebook
couchbase-examples/vector-search-cookbook pull request #3
Opened 2024-08-08 06:43 UTC by teetangh

2024-08-12 16:50 UTC, nithishr requested changes

2024-08-12 16:50 UTC, nithishr commented on jinaai/requirements.txt
Please pin the dependencies. Otherwise, the demo could break with an incompatible release in the future

2024-08-12 16:50 UTC, nithishr commented on jinaai/search.py
> +        num_batches = (len(texts) + batch_size - 1) // batch_size  # Calculate total number of batches
Do you need this `num_batches`? 
You could just create the batches on the fly in batches of `batch_size`.

2024-08-12 16:50 UTC, nithishr commented on jinaai/search.py
> +def get_env_variable(var_name, default_value=None):
You could do this instead 
```value = os.getenv(var_name, default_value)```

2024-08-12 16:50 UTC, nithishr commented on jinaai/jina_index.json
The Notebook is missing here

2024-08-12 16:50 UTC, nithishr commented on jinaai/search.py
> +from langchain_openai import ChatOpenAI
You should use JinaChat instead

2024-08-14 06:20 UTC, teetangh commented on jinaai/search.py
> +        num_batches = (len(texts) + batch_size - 1) // batch_size  # Calculate total number of batches
done

2024-08-14 07:01 UTC, teetangh commented on jinaai/search.py
> +def get_env_variable(var_name, default_value=None):
okay.done

2024-08-19 07:05 UTC, teetangh commented on jinaai/search.py
> +from langchain_openai import ChatOpenAI
used JinaChat now. However, JinaChat internally uses very old version of openai and breaks on updating to newer version

2024-08-20 09:01 UTC, teetangh commented on jinaai/jina_index.json
added

2024-08-20 09:01 UTC, teetangh commented on jinaai/search.py
> +from langchain_openai import ChatOpenAI
updated

2024-08-20 09:05 UTC, teetangh commented on jinaai/requirements.txt
done

2024-08-22 11:42 UTC, nithishr requested changes
Check the comments in #1 as well. Most of them are applicable here as well.

2024-08-22 11:42 UTC, nithishr commented on jinaai/search.py
> +def get_env_variable(var_name, default_value=None):
I don't see it being used here. You are reimplementing things that are part of the standard library.

2024-08-22 11:42 UTC, nithishr commented on jinaai/search.py
> +            # Use the new signature for create_collection
What does this comment mean?

2024-08-22 11:42 UTC, nithishr commented on jinaai/translate.py
> +        raise ValueError(f"{api_name} API key not found")
Check python-dotenv https://github.com/theskumar/python-dotenv

2024-08-22 15:32 UTC, teetangh commented on jinaai/requirements.txt
> +openai==0.27
Actuayll OpenAi is needby JinaChat which breaks unless we install very specific version of openai which 0.27/28. 
The latest version is 1.41

2024-08-22 15:32 UTC, teetangh commented on jinaai/translate.py
I was testing it earlier. will remove it

2024-08-23 05:19 UTC, teetangh commented on jinaai/translate.py
> +        raise ValueError(f"{api_name} API key not found")
Thanks for the info. i was just checking if the API key was working with this file. Will delete translate.py as it is no longer required for RAG.

2024-08-26 08:27 UTC, teetangh commented on jinaai/search.py
> +def get_env_variable(var_name, default_value=None):
done this time

2024-08-26 08:28 UTC, teetangh commented on jinaai/search.py
> +            # Use the new signature for create_collection
removed it

2024-08-26 08:28 UTC, teetangh commented on jinaai/translate.py
removed it

2024-08-29 16:15 UTC, nithishr requested changes
Please recheck the LLM from Jina AI

2024-08-29 16:15 UTC, nithishr commented on jinaai/RAG_with_Couchbase_and_Jina_AI.ipynb
> +        "    llm = JinaChat(temperature=0, jinachat_api_key=JINACHAT_API_KEY, model=\"jina-clip-v1\")\n",
The model looks weird. It is an embedding model & the warning also points to an error.

2024-08-30 07:06 UTC, teetangh commented on jinaai/RAG_with_Couchbase_and_Jina_AI.ipynb
> +        "    llm = JinaChat(temperature=0, jinachat_api_key=JINACHAT_API_KEY, model=\"jina-clip-v1\")\n",
removed it. Now it no longer gives any warning

2024-09-03 18:06 UTC, nithishr approved these changes

2024-09-06 05:45 UTC, merged