DA-535: Couchbase + Anthropic Notebook
couchbase-examples/vector-search-cookbook pull request #4
Opened 2024-08-13 07:20 UTC by teetangh

…de rag

2024-08-22 11:44 UTC, nithishr commented
@teetangh Once you verify that the comments in other PRs are addressed in this one, please ask for review again.

2024-08-29 16:33 UTC, nithishr requested changes

2024-08-30 09:32 UTC, teetangh commented on claudeai/RAG_with_Couchbase_and_Claude.ipynb
> +        "To build our semantic search engine, we need a robust set of tools. The libraries we install handle everything from connecting to databases to performing complex machine learning tasks. Each
Changed to OpenAI embeddings everywhere

2024-08-30 09:32 UTC, teetangh commented on claudeai/RAG_with_Couchbase_and_Claude.ipynb
> +        "In this guide, we will walk you through building a powerful semantic search engine using Couchbase as the backend database, [OpenAi](https://openai.com/) as the AI-powered embedding and [Cla
changed

2024-08-30 09:32 UTC, teetangh commented on claudeai/RAG_with_Couchbase_and_Claude.ipynb
> +        "Embeddings are at the heart of semantic search. They are numerical representations of text that capture the semantic meaning of the words and phrases. Unlike traditional keyword-based search
Changed to OpenAI embeddings everywhere

2024-09-03 18:13 UTC, nithishr requested changes

2024-09-03 18:13 UTC, nithishr commented on claudeai/RAG_with_Couchbase_and_Claude(by_Anthropic).ipynb
> +        "In this section, we prompt the user to input essential configuration settings needed for integrating Couchbase with Cohere's API. These settings include sensitive information like API keys,
Cohere?

2024-09-03 18:13 UTC, nithishr commented on claudeai/RAG_with_Couchbase_and_Claude(by_Anthropic).ipynb
> +        "# Creating the OpenAi Language Model (LLM)\n",
OpenAI

2024-09-03 18:13 UTC, nithishr commented on claudeai/RAG_with_Couchbase_and_Claude(by_Anthropic).ipynb
> +        "Language models are AI systems that are trained to understand and generate human language. We'll be using OpenAI's language model to process user queries and generate meaningful responses. T
Is it using OpenAI's LLM?

2024-09-03 18:13 UTC, nithishr commented on claudeai/RAG_with_Couchbase_and_Claude(by_Anthropic).ipynb
> +        "# Retrieval-Augmented Generation (RAG) with Couchbase and Langchain\n",
LangChain

2024-09-06 06:34 UTC, teetangh commented on claudeai/RAG_with_Couchbase_and_Claude(by_Anthropic).ipynb
> +        "# Creating the OpenAi Language Model (LLM)\n",
Fixed and Changed to Claude 3.5 Sonnet Language model.

2024-09-06 06:34 UTC, teetangh commented on claudeai/RAG_with_Couchbase_and_Claude(by_Anthropic).ipynb
> +        "Language models are AI systems that are trained to understand and generate human language. We'll be using OpenAI's language model to process user queries and generate meaningful responses. T
Fixed and Changed to Claude 3.5 Sonnet Language model.

2024-09-06 06:34 UTC, teetangh commented on claudeai/RAG_with_Couchbase_and_Claude(by_Anthropic).ipynb
> +        "# Retrieval-Augmented Generation (RAG) with Couchbase and Langchain\n",
Fixed

2024-09-06 06:34 UTC, teetangh commented on claudeai/RAG_with_Couchbase_and_Claude(by_Anthropic).ipynb
> +        "In this section, we prompt the user to input essential configuration settings needed for integrating Couchbase with Cohere's API. These settings include sensitive information like API keys,
Removed

2024-09-06 10:20 UTC, nithishr approved these changes

2024-09-06 16:39 UTC, merged