DA-537: Couchbase and Auzre Notbooks
couchbase-examples/vector-search-cookbook pull request #6
Opened 2024-08-27 08:36 UTC by teetangh

2024-08-29 16:43 UTC, nithishr commented on azure/RAG_with_Couchbase_and_Azure.ipynb
I think we should mention the models as AzureOpenAI & not simply Azure

2024-08-30 09:42 UTC, teetangh commented on azure/RAG_with_Couchbase_and_Azure.ipynb
changed to AzureOpenAI everywhere

2024-09-03 18:20 UTC, nithishr requested changes

2024-09-03 18:20 UTC, nithishr commented on azure/RAG_with_Couchbase_and_AzureOpenAI.ipynb
> +        "from langchain_openai import AzureChatOpenAI, AzureOpenAIEmbeddings, ChatOpenAI\n",
Why do you need ChatOpenAI?

2024-09-03 18:20 UTC, nithishr commented on azure/RAG_with_Couchbase_and_AzureOpenAI.ipynb
> +        "# Creating the OpenAi Language Model (LLM)\n",
This is not right.

2024-09-03 18:20 UTC, nithishr commented on azure/RAG_with_Couchbase_and_AzureOpenAI.ipynb
> +        "        openai_api_version=\"2023-03-15-preview\"\n",
Isn't there a newer version of the model? This looks quite old.

2024-09-06 07:37 UTC, teetangh commented on azure/RAG_with_Couchbase_and_AzureOpenAI.ipynb
> +        "from langchain_openai import AzureChatOpenAI, AzureOpenAIEmbeddings, ChatOpenAI\n",
removed it

2024-09-06 07:37 UTC, teetangh commented on azure/RAG_with_Couchbase_and_AzureOpenAI.ipynb
> +        "# Creating the OpenAi Language Model (LLM)\n",
Fixed it

2024-09-06 07:37 UTC, teetangh commented on azure/RAG_with_Couchbase_and_AzureOpenAI.ipynb
> +        "        openai_api_version=\"2023-03-15-preview\"\n",
Now using the latest 2024-07-01-preview

2024-09-06 10:29 UTC, nithishr requested changes

2024-09-06 10:29 UTC, nithishr commented on azure/RAG_with_Couchbase_and_AzureOpenAI.ipynb
> +        "In this section, we prompt the user to input essential configuration settings needed for integrating Couchbase with Cohere's API. These settings include sensitive information like API keys,
Cohere?

2024-09-06 15:20 UTC, teetangh commented on azure/RAG_with_Couchbase_and_AzureOpenAI.ipynb
> +        "In this section, we prompt the user to input essential configuration settings needed for integrating Couchbase with Cohere's API. These settings include sensitive information like API keys,
done

2024-09-09 09:54 UTC, nithishr requested changes

2024-09-09 09:54 UTC, nithishr commented on azure/RAG_with_Couchbase_and_AzureOpenAI.ipynb
> +        "# Loading Sensitive Informnation\n",
Type in Information

2024-09-09 09:54 UTC, nithishr commented on azure/RAG_with_Couchbase_and_AzureOpenAI.ipynb
> +            "RAG Response: The 1929 Great Depression was caused by a combination of factors, including the stock market crash of October 1929, bank failures, reduction in consumer spending and invest
This looks like a Cached response looking at other response times.
Any idea why this is quite a bit faster than other responses?

2024-09-09 09:54 UTC, nithishr commented on azure/RAG_with_Couchbase_and_AzureOpenAI.ipynb
> +        "A vector store is where we'll keep our embeddings. Unlike the FTS index, which is used for text-based search, the vector store is specifically designed to handle embeddings and perform simil
This does not make sense. FTS is used by Couchbase for vector search.

2024-09-10 07:38 UTC, teetangh commented on azure/RAG_with_Couchbase_and_AzureOpenAI.ipynb
> +            "RAG Response: The 1929 Great Depression was caused by a combination of factors, including the stock market crash of October 1929, bank failures, reduction in consumer spending and invest
By rerunning all cells in the notebook(and clearing azure and cache collectionseverytime), I have tried other questions like: "what is photosynthesis", "Why do heavier objects travel downhill faster?",etc.
The first response always comes under 5 seconds.
Conclusion: Natural response time is under 5 seconds, Cache resonse time is under 2 seconds, the response time you are seeing of >40 or >50 seconds is because i am using the S0 free tier of Azure, which rate limits and retries is 60 seconds.

2024-09-10 07:45 UTC, teetangh commented on azure/RAG_with_Couchbase_and_AzureOpenAI.ipynb
> +        "A vector store is where we'll keep our embeddings. Unlike the FTS index, which is used for text-based search, the vector store is specifically designed to handle embeddings and perform simil
fixed it

2024-09-10 07:45 UTC, teetangh commented on azure/RAG_with_Couchbase_and_AzureOpenAI.ipynb
> +        "# Loading Sensitive Informnation\n",
fixed it

2024-09-10 13:08 UTC, nithishr approved these changes

2024-09-10 17:44 UTC, merged